server:
  # 端口号设置
  port: 2020
  # 编码设置
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  # 设置日期格式
  mvc:
    format:
      date: yyyy-MM-dd

  # 浏览器缓存
  thymeleaf:
    cache: false

  # 数据库配置
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/partymemdev?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.sjtu.pojo
  mapper-locations: classpath:mybatis/dao/*.xml